# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Malolan Santhanakrishnan
tagline:          '[[Blog alloc] init]'
description:      'Software Quality Engineer by the day, iOS Developer by the night!'

author:
  name:           'Malolan Santhanakrishnan'
  email:          malolan.santhanakrishnan@gmail.com
  github:         malolans
  twitter:        malolan_s
  linkedin:       profile/view?id=19146420
  
links:
  rss:            feed.xml
  categories:     categories.html
  tags:           tags.html
  about:          about/index.html
  
paginate:         5
