baseURL = "https://www.malolans.com"
languageCode = "en-us"
title = "Welcome!"
theme = "minimal"
publishDir = "docs"

[params]
    author = "Malolan Santhankrishnan"
    description = "This is the personal page of Malolan Santhanakrishnan."
    githubUsername = "malolans"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand"
    copyright = " "

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.icon]]
    url = "mailto:malolans@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/malolans/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/malolan_s/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/malolan-santhanakrishnan-1304b46/"
    name = "fab fa-linkedin"
    weight = 4